name: Sensecraft CI

on:
  push:
    branches:
      - dev
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js v20.19.0
        uses: actions/setup-node@v4
        with:
          node-version: v20.19.0
      - name: use postgres
        uses: Daniel-Marynicz/postgresql-action@master
        with:
          postgres_image_tag: 17.4-alpine-jwt
          postgres_image_name: conversence/postgres
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25' # Meets the requirement of the crypto library
      - name: Install client components
        run: |
          sudo apt update
          sudo apt install -y postgresql-client
          go install github.com/mailhog/MailHog@latest
          echo "$(go env GOPATH)/bin" >> $GITHUB_PAT
    # - name: Install client components
    #   working-directory: /tmp
    #   run: |
    #     sudo apt update
    #     sudo apt install -y postgresql-client wget
    #     wget -c https://go.dev/dl/go1.24.2.linux-amd64.tar.gz
    #     sudo tar -C /usr/local/ -xzf go1.24.2.linux-amd64.tar.gz
    #     go install github.com/mailhog/MailHog@latest
    #     echo "${HOME}/go/bin" >> $GITHUB_PATH
      - name: Initialize test DB
        working-directory: ./server
        run: python ./scripts/initial_setup.py -u postgres -p postgres --no-create-development --no-create-production --app_name sensecraft
      - name: install postgrest
        run: |
          wget https://github.com/PostgREST/postgrest/releases/download/v14.2/postgrest-v14.2-linux-static-x86-64.tar.xz
          tar -Jxf postgrest-v14.2-linux-static-x86-64.tar.xz
          rm postgrest-v14.2-linux-static-x86-64.tar.xz
          sudo mv postgrest /usr/bin/
      - name: Install server dependencies
        working-directory: ./server
        run: npm ci --legacy-peer-deps
      - name: Build dispatcher
        working-directory: ./server
        run: npm run build
      - name: Run server tests
        working-directory: ./server
        run: npm run test
      - name: Install client dependencies
        working-directory: ./sc-client
        run: |
          npm ci --legacy-peer-deps
      - name: Run client unit tests
        working-directory: ./sc-client
        run: |
          npm run prepare
          npm run test:unit:ci
      - name: Run integration unit tests
        working-directory: ./sc-client
        run: |
          sudo npx playwright install-deps
          npm run playwright:install
          npm run test:playwright
      # - name: Run scoring tests
      #   working-directory: ./sc-client
      #   run: npm run test:scoring
      - name: cleanup postgres container
        run: |
          export PGCONT=`docker ps -q --filter ancestor=conversence/postgres:17.4-alpine-jwt`
          if [[-n $PGCONT]]
          then
            docker container stop $PGCONT
            docker container rm $PGCONT
          fi
